name: Deploy to Railway

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: apps/api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: apps/api
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"
        JWT_SECRET_KEY: "test-secret-key-for-ci"
        ANTHROPIC_API_KEY: "test-api-key"
      run: |
        pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway up --service talk2publish-api
