name: Test Suite

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: apps/api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      working-directory: apps/api
      run: |
        flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run type checking
      working-directory: apps/api
      run: |
        mypy src --ignore-missing-imports
      continue-on-error: true

    - name: Run tests with coverage
      working-directory: apps/api
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"
        JWT_SECRET_KEY: "test-secret-key-for-ci"
        ANTHROPIC_API_KEY: "test-api-key"
      run: |
        pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=html

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: apps/api/htmlcov/index.html
      continue-on-error: true
